### ISSUE TITLE
Argument prefixes not compiled correctly when using javascript expressions

### ISSUE THREAD

**Issue by arunisaac** [arunisaac/ccwl#12]
Something like `#:run ("-pop" "$(inputs.population.nameroot)")` is compiled to
```yaml
arguments:
  - position: 3
     valueFrom: "-pop"
   - position: 4
      valueFrom: $(inputs.population.nameroot)
```

It should rather be compiled to
```yaml
- position: 3
   prefix: "-pop"
   valueFrom: $(inputs.population.nameroot)
```
Thanks to glassofwhiskey for reporting this in the Matrix CWL room!
